### ISSUE TITLE
Unable to open shape predictor

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [amineHorseman/facial-expression-recognition-using-cnn#5] opened 2018-10-02 08:25 UTC
File "G:/Asad/Projects/facial-expression-recognition-using-cnn-master/facial-expression-recognition-using-cnn-master/convert_fer2013_to_images_and_landmarks.py", line 61, in <module>
    predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')

RuntimeError: Unable to open shape_predictor_68_face_landmarks.dat

**Comment by amineHorseman** [comment] 2018-10-10 10:31
Duplicate of #6

**Closed by amineHorseman** 2018-10-10 10:31 UTC
